print("Welcome to the sandwich shop")
print("-----------------------------")
print("Sandwich prices:")
print("-------------------------------------------")
print("Sandwiches              Wraps")
print("-------------------------------------------")
print("Sandwich       £2.80    Wrap          £3.00")
print("With crisps    +30p     With crisps    +30p")
print("-------------------------------------------")
total = 0