print("Once upon a time three bears lived in a little house.")
print("There was a father bear, a mother bear and a baby bear.")
print("One morning the bears made porridge for breakfast,")
print("but the porridge was too hot to eat.")
print("So the bears decided to take a walk to let it cool down.")